import pandas as pd
import json
import os
from typing import Dict, Any, Tuple

class PandasEngine:
    def __init__(self, data_dir: str):
        self.data_dir = data_dir
        self.dataframes: Dict[str, pd.DataFrame] = {}
        
    def load_file(self, filename: str) -> bool:
        """Loads a CSV or Excel file into the engine."""
        file_path = os.path.join(self.data_dir, filename)
        if not os.path.exists(file_path):
            return False
            
        try:
            if filename.endswith('.csv'):
                self.dataframes[filename] = pd.read_csv(file_path)
            elif filename.endswith('.xlsx'):
                self.dataframes[filename] = pd.read_excel(file_path)
            else:
                return False
            return True
        except Exception as e:
            print(f"Error loading {filename}: {e}")
            return False
            
    def get_profile(self, filename: str) -> Dict[str, Any]:
        """Returns metadata about the dataframe to feed to the LLM."""
        if filename not in self.dataframes:
            if not self.load_file(filename):
                return {"error": "File not loaded or not found."}
                
        df = self.dataframes[filename]
        
        profile = {
            "filename": filename,
            "rows": len(df),
            "columns": list(df.columns),
            "dtypes": {col: str(dtype) for col, dtype in df.dtypes.items()},
            "sample_data": df.head(3).to_dict(orient="records"),
            "numerical_summary": df.describe().to_dict()
        }
        
        # Convert index objects to list to avoid JSON serialization errors down the line
        return profile
    
    def execute_python_code(self, filename: str, code: str) -> Any:
        """
        Executes raw python code generated by the LLM on the dataframe.
        The code is expected to define a function `analyze(df)` that returns a dictionary.
        This provides deterministic math/KPIs.
        """
        print(f"\n[PandasEngine] Executing code on file: {filename}")
        if filename not in self.dataframes:
            print(f"[PandasEngine] Loading {filename} into memory...")
            self.load_file(filename)
            
        df = self.dataframes.get(filename)
        if df is None:
            print(f"[PandasEngine] Dataframe not found after load attempt!")
            return {"error": "Dataframe not found."}
            
        # Dangerous eval/exec boundary 
        # In a strict production environment, this should be sandboxed or rely on a safer DSL
        local_env = {"df": df, "pd": pd}
        try:
            exec(code, local_env)
            if 'analyze' in local_env:
                result = local_env['analyze'](df)
                return result
            else:
                print("[PandasEngine] ERROR: 'analyze(df)' function was not defined by the LLM code.")
                return {"error": "Code must define an 'analyze(df)' function."}
        except Exception as e:
            print(f"[PandasEngine] Python Execution ERROR: {str(e)}")
            return {"error": str(e)}

# Singleton instance setup placeholder
# pandas_engine = PandasEngine(DATA_DIR)
